import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:myboss_mobile/core/di/injection.dart';
import 'package:myboss_mobile/core/session/session_manager.dart';
import 'package:myboss_mobile/core/error/failure_message_mapper.dart';
import 'package:myboss_mobile/core/localization/app_localizations.dart';
import 'package:myboss_mobile/core/theme/app_colors.dart';
import 'package:myboss_mobile/core/widgets/boss_buttons.dart';
import 'package:myboss_mobile/core/widgets/boss_design_widgets.dart';
import 'package:myboss_mobile/features/squad/domain/entities/squad.dart';
import 'package:myboss_mobile/features/squad/presentation/cubit/create_squad_cubit.dart';
import 'package:myboss_mobile/features/squad/presentation/squad_formation_navigation.dart';

class CreateSquadPage extends StatelessWidget {
  const CreateSquadPage({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => getIt<CreateSquadCubit>(),
      child: const _CreateSquadView(),
    );
  }
}

class _CreateSquadView extends StatefulWidget {
  const _CreateSquadView();

  @override
  State<_CreateSquadView> createState() => _CreateSquadViewState();
}

class _CreateSquadViewState extends State<_CreateSquadView> {
  final _nameController = TextEditingController();
  String _selectedBadge = squadBadges.first;

  @override
  void dispose() {
    _nameController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final session = getIt<SessionManager>();
    final user = session.currentUser;
    final l10n = AppLocalizations.of(context);

    return Scaffold(
      backgroundColor: AppColors.cloud,
      body: BlocConsumer<CreateSquadCubit, CreateSquadState>(
        listener: (context, state) {
          if (state is CreateSquadSuccess) {
            session.setSquad(state.squad);
            context.go('/squad/success', extra: {'mode': 'create', 'squad': state.squad});
          }
        },
        builder: (context, state) {
          final isLoading = state is CreateSquadSubmitting;
          final errorFailure = state is CreateSquadError ? state.failure : null;
          final error = errorFailure != null ? localizedFailureMessage(l10n, errorFailure) : null;
          final canSubmit = user != null && _nameController.text.trim().isNotEmpty;

          return Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              BossTopBar(onBack: () => popSquadFormationRoute(context)),
              Expanded(
                child: BossScreenPad(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      Text(l10n.createSquadNameTitle, style: AppTextStyles.h1),
                      const SizedBox(height: 8),
                      Text(l10n.createSquadNameDesc, style: AppTextStyles.muted),
                      const SizedBox(height: 20),
                      BossField(
                        leading: const Text('🏷️', style: TextStyle(fontSize: 18)),
                        child: TextField(
                          controller: _nameController,
                          autofocus: true,
                          textInputAction: TextInputAction.done,
                          decoration: InputDecoration(
                            isDense: true,
                            border: InputBorder.none,
                            hintText: l10n.squadNameHint,
                            hintStyle: const TextStyle(color: AppColors.grey400),
                          ),
                          onChanged: (_) => setState(() {}),
                        ),
                      ),
                      const SizedBox(height: 10),
                      BossField(
                        leading: const Text('#', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700)),
                        backgroundColor: const Color(0xFFEBEBEB),
                        enabled: false,
                        child: Text(l10n.squadIdAutoGenerated, style: AppTextStyles.small),
                      ),
                      const SizedBox(height: 18),
                      Text(l10n.pickBadge, style: const TextStyle(fontWeight: FontWeight.w700, fontSize: 13, color: AppColors.ink)),
                      const SizedBox(height: 8),
                      Wrap(
                        spacing: 8,
                        runSpacing: 8,
                        children: squadBadges.map((badge) {
                          final selected = _selectedBadge == badge;
                          return GestureDetector(
                            onTap: () => setState(() => _selectedBadge = badge),
                            child: Container(
                              width: 52,
                              height: 52,
                              alignment: Alignment.center,
                              decoration: BoxDecoration(
                                color: selected ? AppColors.ink : AppColors.white,
                                borderRadius: BorderRadius.circular(14),
                                border: Border.all(color: selected ? AppColors.ink : AppColors.grey200, width: 1.5),
                              ),
                              child: Text(badge, style: const TextStyle(fontSize: 24)),
                            ),
                          );
                        }).toList(),
                      ),
                      const SizedBox(height: 18),
                      BossCard(
                        child: Row(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const Text('👑', style: TextStyle(fontSize: 20)),
                            const SizedBox(width: 10),
                            Expanded(child: Text(l10n.createSquadLeaderHint, style: AppTextStyles.small)),
                          ],
                        ),
                      ),
                      const SizedBox(height: 18),
                      if (error != null)
                        Padding(
                          padding: const EdgeInsets.only(bottom: 12),
                          child: Text(error, style: const TextStyle(color: AppColors.error), textAlign: TextAlign.center),
                        ),
                      BossPrimaryButton(
                        label: l10n.createSquad,
                        variant: BossButtonVariant.brand,
                        isLoading: isLoading,
                        onPressed: canSubmit
                            ? () => context.read<CreateSquadCubit>().submit(
                                  name: _nameController.text.trim(),
                                  badge: _selectedBadge,
                                  leaderId: user!.id,
                                  leaderFirstName: user.firstName,
                                  leaderLastName: user.lastName,
                                  governorate: user.governorate ?? '',
                                  building: user.buildingName,
                                )
                            : null,
                      ),
                    ],
                  ),
                ),
              ),
            ],
          );
        },
      ),
    );
  }
}
